---
##################################################
# Name: ci-build-canisters.yaml
# Description: CI Build checks verifying canisters
##################################################
name: CI Build Canisters
on: workflow_call

env:
  NIXPKGS_ALLOW_UNFREE: 1
  SECRETSPEC_PROVIDER: env

jobs:
  build-canisters:
    name: CI Build Canister ${{ matrix.canister }}
    runs-on: ubuntu-latest
    timeout-minutes: 120

    strategy:
      fail-fast: false
      matrix:
        include:
          - canister: ic_siwa_provider
            type: rust
          - canister: test_canister_rs
            type: rust
          - canister: test_canister_ts
            type: assets

    steps:
      - id: checkout_repository
        name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - id: setup_devenv
        name: Setup Devenv
        uses: ./.github/actions/setup-devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-cache-name: ${{ vars.CACHIX_CACHE_NAME }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - id: cache_cargo
        name: Cache Cargo
        uses: ./.github/actions/cache-cargo
        with:
          cache-key-prefix: ci-build

      - id: cache_bun
        name: Cache Bun
        uses: ./.github/actions/cache-bun

      - id: build_canister
        name: Build Canister
        uses: ./.github/actions/build-canister
        with:
          canister: ${{ matrix.canister }}
          type: ${{ matrix.type }}
          environment: development

      - id: upload_artifact
        name: Upload Build Artifact
        if: matrix.canister == 'ic_siwa_provider'
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.canister }}-ci
          path: target/wasm32-unknown-unknown/release/${{ matrix.canister }}.wasm
          retention-days: 1
